services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: bigdata-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bigdata-network

  backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    restart: always
    container_name: bigdata-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - bigdata-network
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    container_name: bigdata-frontend
    depends_on:
      - backend
    networks:
      - bigdata-network
  nginx:
    image: nginx:alpine
    restart: always
    container_name: bigdata-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - bigdata-network
volumes:
  postgres_data:

networks:
  bigdata-network:
    driver: bridge
